#!/usr/bin/env bash
#implements case statements

number=1
while ((number<=20)); do
	echo "$number"
	case $number in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	number=$((number+1))
done
