#!/usr/bin/env bash
#display time for 12 hours 59 minutes

hours=0
minutes=1
while ((hours<=12)); do
	echo "Hour: $hours"
	while ((minutes<=59)); do
		echo "$minutes"
		minutes=$((minutes+1))
	done
	minutes=1
	hours=$((hours+1))
done
