#!/usr/bin/env bash
#display current directory content in list form
#Where only the part of the name after the first dash is displayed:
#1-test_file wil be displayed as test_file

dir_list=$(ls)
for file in $dir_list; do
	echo "$file" | cut -d "-" -f2 
done
