#!/usr/bin/env bash
#displays numbers from 1 - 100

number=1
while ((number<=100)); do
	if ((number%3==0)) && ((number%5==0)); then
		echo "FizzBuzz"
	elif ((number%3==0)); then
		echo "Fizz"
	elif ((number%5==0)); then
		echo "Buzz"
	else echo "$number"
	fi
	number=$((number+1))
done
